name: draft release

on:
  push:
    branch:
      - main

jobs:
  draft-release:
    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@09c613e259eb8d4e7c81c2cb00618eb5fc4575a7 # v5
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB }}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Prisma Cloud 
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: https://api.ind.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
